--- 
version: '2'

services:
  moh:
    image: webitel/freeswitch-sound:moh
    container_name: moh
    network_mode: "none"
  en:
    image: webitel/freeswitch-sound:en
    container_name: en
    network_mode: "none"
  client:
    image: "webitel/client:${WEBITEL_VERSION}"
    container_name: web-client
    network_mode: "none"
  mongo:
    image: mongo:3
    container_name: mongo
    restart: always
    volumes:
      - "${WEBITEL_DIR}/mongodb:/data/db"
    ports:
      - "172.17.0.1:27017:27017"
    command: --storageEngine wiredTiger
    networks:
      - wtel
    ulimits:
      nproc: 65535
      nofile: 65535
  acr:
    image: "webitel/acr:${WEBITEL_VERSION}"
    container_name: acr
    restart: always
    env_file: "${DIR}/env/common"
    ports:
      - "172.17.0.1:10030:10030"
    depends_on:
      - mongo
    networks:
      - wtel
  wconsole:
    image: "webitel/wconsole:${WEBITEL_VERSION}"
    container_name: wconsole
    privileged: true
    restart: always
    env_file: "${DIR}/env/common"
    environment: 
      - "ROOT_PASSWORD=${WEBITEL_PASS}"
    volumes:
      - "${WEBITEL_DIR}/db:/webitel/db"
    ports:
      - "172.17.0.1:10024:10024"
    depends_on:
      - mongo
    networks:
      - wtel
  engine:
    image: "webitel/engine:${WEBITEL_VERSION}"
    container_name: engine
    env_file: "${DIR}/env/common"
    restart: always
    ports:
      - "172.17.0.1:10022:10022"
    depends_on:
      - mongo
      - wconsole
      - freeswitch
    environment:
      - "application:auth:tokenSecretKey=${WEBITEL_KEY}"
      - "webitelServer:secret=${WEBITEL_PASS}"
      - "cdrServer:host=${WEBITEL_PROTO}://${WEBITEL_HOST}/cdr/"
      - "broker:connectionString=esl://ClueCon:ClueCon@172.17.0.1:8021"
    networks:
      - wtel
  storage:
    image: "webitel/storage:${WEBITEL_VERSION}"
    container_name: storage
    restart: always
    ports:
      - "172.17.0.1:10021:10021"
      - "172.17.0.1:10023:10023"
      - "172.17.0.1:10025:10025"
    env_file:
      - "${DIR}/env/common"
      - "${DIR}/env/storage"
    environment:
      - "application:auth:tokenSecretKey=${WEBITEL_KEY}"
    volumes:
      - "${WEBITEL_DIR}/recordings:/recordings"
    depends_on:
      - mongo
    networks:
      - wtel
  freeswitch:
    image: "webitel/freeswitch:${WEBITEL_VERSION}"
    container_name: freeswitch
    restart: always
    privileged: true
    network_mode: "host"
    env_file: "${DIR}/env/freeswitch"
    volumes:
      - fs-data:/recordings
      - "${WEBITEL_DIR}/lua:/scripts/lua"
      - "${WEBITEL_DIR}/ssl:/certs"
    volumes_from:
      - moh
      - en
  nginx:
    image: "webitel/nginx:${WEBITEL_VERSION}"
    container_name: nginx
    restart: always
    environment:
      - "WEBITEL_HOST=${WEBITEL_HOST}"
      - "WEBITEL_SSL=${WEBITEL_SSL}"
    volumes:
      - "${WEBITEL_DIR}/ssl:/etc/nginx/ssl"
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - client
    depends_on:
      - engine
      - storage
    networks:
      - wtel
  
volumes:
  fs-data:
  
networks:
  wtel:
    driver: bridge
