--- 
version: '2'

services:
  mongo:
    image: mongo:3.4
    container_name: mongo
    restart: always
    volumes:
      - "${WEBITEL_DIR}/mongodb:/data/db"
    ports:
      - "172.17.0.1:27017:27017"
    command: --storageEngine wiredTiger
    networks:
      - wtel
    ulimits:
      nproc: 65535
      nofile: 65535
  acr:
    image: "webitel/acr:${WEBITEL_VERSION}"
    container_name: acr
    restart: always
    env_file: "${DIR}/env/common"
    environment:
      - "broker:enable=false"
    ports:
      - "172.17.0.1:10030:10030"
    depends_on:
      - mongo
    networks:
      - wtel
  wconsole:
    image: "webitel/wconsole:${WEBITEL_VERSION}"
    container_name: wconsole
    privileged: true
    restart: always
    env_file: "${DIR}/env/common"
    environment: 
      - "ROOT_PASSWORD=${WEBITEL_PASS}"
    volumes:
      - "${WEBITEL_DIR}/db:/webitel/db"
    ports:
      - "172.17.0.1:10024:10024"
    depends_on:
      - mongo
    networks:
      - wtel
  engine:
    image: "webitel/engine:${WEBITEL_VERSION}"
    container_name: engine
    env_file: "${DIR}/env/common"
    restart: always
    ports:
      - "172.17.0.1:10022:10022"
    depends_on:
      - mongo
      - wconsole
      - freeswitch
    environment:
      - "webitelServer:secret=${WEBITEL_PASS}"
      - "cdrServer:host=${WEBITEL_PROTO}://${WEBITEL_HOST}/cdr/"
      - "broker:connectionString=esl://ClueCon:ClueCon@172.17.0.1:8021"
    volumes:
      - "${WEBITEL_DIR}/ssl:/ssl"
    networks:
      - wtel
  storage:
    image: "webitel/storage:${WEBITEL_VERSION}"
    container_name: storage
    restart: always
    ports:
      - "172.17.0.1:10021:10021"
      - "172.17.0.1:10023:10023"
      - "172.17.0.1:10025:10025"
    env_file:
      - "${DIR}/env/common"
      - "${DIR}/env/storage"
    environment:
      - "broker:enable=false"
      - "elastic:enabled=false"
    volumes:
      - "${WEBITEL_DIR}/ssl:/ssl"
      - "${WEBITEL_DIR}/recordings:/recordings"
      - storage:/cdr/cache
    depends_on:
      - mongo
    networks:
      - wtel
  freeswitch:
    image: "webitel/freeswitch:${WEBITEL_VERSION}"
    container_name: freeswitch
    restart: always
    privileged: true
    network_mode: "host"
    env_file: "${DIR}/env/freeswitch"
    tmpfs: /db
    volumes:
      - fs-data:/recordings
      - fs-sounds:/sounds      
      - "${WEBITEL_DIR}/lua:/scripts/lua"
      - "${WEBITEL_DIR}/ssl:/certs"
  nginx:
    image: "webitel/nginx:${WEBITEL_VERSION}"
    container_name: nginx
    restart: always
    environment:
      - "WEBITEL_HOST=${WEBITEL_HOST}"
      - "WEBITEL_SSL=${WEBITEL_SSL}"
      - "elastic:enabled=false"
    volumes:
      - "${WEBITEL_DIR}/ssl:/etc/nginx/ssl"
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "kibana:172.17.0.1"
    depends_on:
      - engine
      - storage
    networks:
      - wtel
  
volumes:
  storage:
  fs-data:
  fs-sounds:
  
networks:
  wtel:
    driver: bridge
