--- 
version: '2'

services:
  mongo-repair:
    image: mongo:3.4
    restart: always
    volumes:
      - "${WEBITEL_DIR}/mongodb:/data/db"
    command: --repair
    ulimits:
      nproc: 65535
      nofile: 65535
  elasticsearch5:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    container_name: elasticsearch5
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - path.repo=/usr/share/elasticsearch/data/backups
    ulimits:
      memlock: -1
      nofile: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - "${WEBITEL_DIR}/elasticsearch5:/usr/share/elasticsearch/data"
  elasticsearch6:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1
    container_name: elasticsearch6
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - path.repo=/usr/share/elasticsearch/data/backups
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "${WEBITEL_DIR}/esdata6:/usr/share/elasticsearch/data"
