sudo: required
language: bash

services: 
  - docker

before_install:
  - docker-compose -f dev/docker-compose.yml pull

install:  
  - docker-compose -f dev/docker-compose.yml up -d

script:  
  - curl -X POST -H 'Content-Type: application/json' -d '{"username":"root","password":"secret"}' "http://'${WEBITEL_HOST}'/engine/login"

