--- 
version: '2'

services:
  elasticsearch:
    image: elasticsearch:2.3
    container_name: elasticsearch
    ports:
      - "172.17.0.1:9200:9200"
    volumes:
      - "${WEBITEL_DIR}/elastic:/usr/share/elasticsearch/data"
    command: -Des.node.name="Webitel"
    networks:
      - wtel
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ports:
      - "172.17.0.1:5672:5672"
    environment:
      - "RABBITMQ_DEFAULT_USER=webitel"
      - "RABBITMQ_DEFAULT_PASS=${WEBITEL_PASS}"
    networks:
      - wtel
  moh:
    image: webitel/freeswitch-sound:moh
    container_name: moh
    network_mode: "none"
  en:
    image: webitel/freeswitch-sound:en
    container_name: en
    network_mode: "none"
  ru:
    image: webitel/freeswitch-sound:ru
    container_name: ru
    network_mode: "none"
  client:
    image: "webitel/client:${WEBITEL_VERSION}"
    container_name: web-client
    network_mode: "none"
  mongo:
    image: mongo:3
    container_name: mongo
    volumes:
      - "${WEBITEL_DIR}/mongodb:/data/db"
    ports:
      - "172.17.0.1:27017:27017"
    command: --storageEngine wiredTiger
    networks:
      - wtel
    ulimits:
      nproc: 65535
      nofile: 65535
  kibana:
    image: "webitel/kibana:${WEBITEL_VERSION}"
    container_name: kibana
    environment:
      - "ENGINE_URL=${WEBITEL_PROTO}://${WEBITEL_HOST}/engine/"
      - "FS_URL=${WEBITEL_WS}://${WEBITEL_HOST}/verto/"
    ports:
      - "5601"
    depends_on:
      - elasticsearch
    networks:
      - wtel
  acr:
    image: "webitel/acr:${WEBITEL_VERSION}"
    container_name: acr
    restart: always
    env_file: "${DIR}/env/common"
    ports:
      - "172.17.0.1:10030:10030"
    depends_on:
      - mongo
    networks:
      - wtel
  wconsole:
    image: "webitel/wconsole:${WEBITEL_VERSION}"
    container_name: wconsole
    privileged: true
    restart: always
    env_file: "${DIR}/env/common"
    environment: 
      - "ROOT_PASSWORD=${WEBITEL_PASS}"
    volumes:
      - "${WEBITEL_DIR}/db:/webitel/db"
    ports:
      - "172.17.0.1:10024:10024"
    depends_on:
      - mongo
    networks:
      - wtel
  engine:
    image: "webitel/engine:${WEBITEL_VERSION}"
    container_name: engine
    env_file: "${DIR}/env/common"
    restart: always
    ports:
      - "172.17.0.1:10022:10022"
    depends_on:
      - mongo
      - rabbitmq
      - wconsole
      - freeswitch
    environment:
      - "application:auth:tokenSecretKey=${WEBITEL_KEY}"
      - "webitelServer:secret=${WEBITEL_PASS}"
      - "cdrServer:host=${WEBITEL_PROTO}://${WEBITEL_HOST}/cdr/"
      - "broker:connectionString=amqp://webitel:${WEBITEL_PASS}@rabbitmq?heartbeat=0"
    networks:
      - wtel
  cdr:
    image: "webitel/cdr-server:${WEBITEL_VERSION}"
    container_name: cdr
    restart: always
    ports:
      - "172.17.0.1:10021:10021"
      - "172.17.0.1:10023:10023"
    env_file:
      - "${DIR}/env/common"
      - "${DIR}/env/cdr"
    environment:
      - "application:auth:tokenSecretKey=${WEBITEL_KEY}"
    volumes:
      - "${WEBITEL_DIR}/recordings:/recordings"
    depends_on:
      - elasticsearch
      - mongo
    networks:
      - wtel
  freeswitch:
    image: "webitel/freeswitch:${WEBITEL_VERSION}"
    container_name: freeswitch
    restart: always
    privileged: true
    network_mode: "host"
    env_file: "${DIR}/env/freeswitch"
    volumes:
      - fs-data:/recordings
      - "${WEBITEL_DIR}/lua:/scripts/lua"
      - "${WEBITEL_DIR}/ssl:/certs"
    volumes_from:
      - moh
      - en
      - ru
    depends_on:
      - rabbitmq
  nginx:
    image: "webitel/nginx:${WEBITEL_VERSION}"
    container_name: nginx
    environment:
      - "WEBITEL_HOST=${WEBITEL_HOST}"
      - "WEBITEL_SSL=${WEBITEL_SSL}"
    volumes:
      - "${WEBITEL_DIR}/ssl:/etc/nginx/ssl"
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - client
    depends_on:
      - engine
    networks:
      - wtel
  
volumes:
  fs-data:
  
networks:
  wtel:
    driver: bridge
