--- 
version: '2'

services:
  elasticsearch:
    image: elasticsearch:2
    container_name: elasticsearch
    ports:
      - "172.17.0.1:9200:9200"
    volumes:
      - "${WEBITEL_DIR}/elasticsearch:/usr/share/elasticsearch/data"
    command: -Des.node.name="Webitel"
    networks:
      - net
  fluent:
    image: webitel/fluentd
    container_name: fluentd
    ports:
      - "172.17.0.1:24224:24224"
    networks:
      - net
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ports:
      - "172.17.0.1:5672:5672"
    environment:
      - "RABBITMQ_DEFAULT_USER=webitel"
      - "RABBITMQ_DEFAULT_PASS=${WEBITEL_PASS}"
    networks:
      - net
    
networks:
  net:
    driver: bridge