---
- sysctl:
    name: net.core.rmem_max
    value: 16777216
    sysctl_set: yes
    state: present

- sysctl:
    name: net.core.netdev_max_backlog
    value: 4096
    sysctl_set: yes
    state: present

- sysctl:
    name: net.core.wmem_max
    value: 16777216
    sysctl_set: yes
    state: present

- sysctl:
    name: net.core.somaxconn
    value: 4096
    sysctl_set: yes
    state: present

- sysctl:
    name: vm.min_free_kbytes
    value: 65536
    sysctl_set: yes
    state: present

- sysctl:
    name: vm.max_map_count
    value: 2621445
    sysctl_set: yes
    state: present
    reload: yes
